apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eimza-api
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [eimza]
  selector:
    matchLabels:
      app.kubernetes.io/name: eimza-api
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
