apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: eimza-api
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext/runAsUser
      - op: remove
        path: /spec/template/spec/securityContext/runAsGroup
      - op: remove
        path: /spec/template/spec/securityContext/fsGroup
